site_name: My Docs
theme:
  name: material
site_url: https://tonybustamante.github.com
nav:
  - Home: index.md
  - Setting up github pages: gh-pages_setup.md
  - Configuring windows git w/ SSH: ssl_refresher.md